"""Cross-check the kernel's enclosures against independently known digits.

    python tests/test_exact.py

Exit code 1 on any failure.

WHY THIS FILE EXISTS
    `core/exact.py` says its irrational constants are "cross-checked against
    independently known digit strings in tests/test_exact.py". The file was not
    in the tree. A claim of certification with no test behind it is the one kind
    of claim this kernel exists to avoid making.

    The digit strings below are quoted from published decimal expansions, not
    generated by this code. That is the point: a kernel that checks itself
    against itself checks nothing.

WHAT IS ACTUALLY BEING TESTED
    Not accuracy -- containment. An interval is correct when the true value lies
    inside it, however wide it is. A too-wide interval is useless but honest; an
    interval that excludes the true value is a broken proof. Every assertion here
    is of the form "the known value lies within the computed interval", plus
    checks that arithmetic widens outward rather than inward.
"""
from __future__ import annotations

import sys
from fractions import Fraction as F
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / 'src'))

from certivl import (  # noqa: E402
    Ivl, abs_ivl, asin_ivl, atan_ivl, cos_ivl, deg, isolate_root, isqrt_ivl,
    pi_ivl, sec_ivl, sin_ivl, sqrt2, sqrt3, sqrt_ivl, tan_ivl,
)

# Published expansions. None of these came from this code.
PI = ("3.14159265358979323846264338327950288419716939937510"
      "58209749445923078164062862089986280348253421170679")
SQRT2 = ("1.41421356237309504880168872420969807856967187537694"
         "80731766797379907324784621070388503875343276415727")
SQRT3 = ("1.73205080756887729352744634150587236694280525381038"
         "06280558069794519330169088000370811461867572485757")
SQRT5 = ("2.23606797749978969640917366873127623544061835961152"
         "57242708972454105209256378048994144144083787822749")
SIN1 = "0.84147098480789650665250232163029899962256306079837"
COS1 = "0.54030230586813971740093660744297660373231042061792"
ATAN1 = "0.78539816339744830961566084581987572104929234984378"

FAILURES: list[str] = []


def as_fraction(decimal: str) -> F:
    whole, _, frac = decimal.partition(".")
    return F(int(whole + frac), 10 ** len(frac))


def check(name: str, iv, decimal: str) -> None:
    """The published digits must agree with the interval to their own precision.

    A published expansion is truncated, so as an exact rational it sits just
    below the true value -- by up to one unit in its last place. The kernel's
    enclosures are far narrower than that: pi comes out 2e-80 wide against a
    50-digit string whose truncation error is 1e-50. Asking whether the
    truncated rational lies inside the interval therefore fails on a correct
    kernel, which is what it did on the first run of this file.

    The honest comparison is at the precision actually published: the interval
    and the published value must agree to within one unit in the last digit
    given.
    """
    true = as_fraction(decimal)
    ulp = F(1, 10 ** (len(decimal) - decimal.index(".") - 1))
    ok = iv.lo - ulp <= true <= iv.hi + ulp
    width = float(iv.hi - iv.lo)
    print(f"  {'ok  ' if ok else 'FAIL'} {name:<14} width {width:.3e}"
          + ("" if ok else f"   [{float(iv.lo)}, {float(iv.hi)}] excludes {decimal[:22]}"))
    if not ok:
        FAILURES.append(name)


def check_true(name: str, cond: bool, detail: str = "") -> None:
    print(f"  {'ok  ' if cond else 'FAIL'} {name}" + ("" if cond else "   " + detail))
    if not cond:
        FAILURES.append(name)


def overlaps(a, b) -> bool:
    return not (a.hi < b.lo or b.hi < a.lo)


def main() -> int:
    print("constants against published digits")
    check("pi", pi_ivl(), PI)
    check("sqrt(2)", sqrt_ivl(2), SQRT2)
    check("sqrt(3)", sqrt_ivl(3), SQRT3)
    check("sqrt(5)", sqrt_ivl(5), SQRT5)
    check("sqrt2()", sqrt2(), SQRT2)
    check("sqrt3()", sqrt3(), SQRT3)

    print("\ntranscendental functions at 1 radian")
    check("sin(1)", sin_ivl(Ivl(1, 1)), SIN1)
    check("cos(1)", cos_ivl(Ivl(1, 1)), COS1)
    check("atan(1)", atan_ivl(Ivl(1, 1)), ATAN1)

    print("\nidentities that must hold inside the enclosures")
    s, c = sin_ivl(Ivl(1, 1)), cos_ivl(Ivl(1, 1))
    one = s * s + c * c
    check_true("sin^2 + cos^2 encloses 1", one.lo <= 1 <= one.hi,
               f"[{float(one.lo)}, {float(one.hi)}]")
    check_true("tan(1) agrees with sin/cos",
               overlaps(tan_ivl(Ivl(1, 1)), s / c))
    check_true("sec(1) agrees with 1/cos",
               overlaps(sec_ivl(Ivl(1, 1)), Ivl(1, 1) / c))
    check_true("asin(1/2) encloses pi/6",
               overlaps(asin_ivl(Ivl(F(1, 2), F(1, 2))),
                        pi_ivl() * Ivl(F(1, 6), F(1, 6))))
    check_true("deg(90) encloses pi/2",
               overlaps(deg(90), pi_ivl() * Ivl(F(1, 2), F(1, 2))))

    print("\ncontainment under arithmetic (outward rounding)")
    a, b = Ivl(F(1, 3), F(1, 2)), Ivl(F(2, 7), F(3, 7))
    check_true("add keeps both exact endpoints",
               (a + b).lo <= F(1, 3) + F(2, 7) and F(1, 2) + F(3, 7) <= (a + b).hi)
    check_true("sub keeps both exact endpoints",
               (a - b).lo <= F(1, 3) - F(3, 7) and F(1, 2) - F(2, 7) <= (a - b).hi)
    prod = a * b
    corners = [x * y for x in (F(1, 3), F(1, 2)) for y in (F(2, 7), F(3, 7))]
    check_true("mul encloses every corner",
               prod.lo <= min(corners) and max(corners) <= prod.hi)
    # Containment, not tightness. Ivl(-2,3)**2 returns [-6, 9], which encloses
    # the true range [0, 9] and is therefore correct under this kernel's stated
    # invariant. A tighter square would return [0, 9]; the loose one cannot
    # produce a false proof, only a weaker one.
    sq = Ivl(-2, 3) ** 2
    check_true("square encloses the true range [0, 9]",
               sq.lo <= 0 and 9 <= sq.hi, f"[{float(sq.lo)}, {float(sq.hi)}]")
    check_true("abs of a spanning interval starts at 0",
               abs_ivl(Ivl(-5, 2)).lo == 0)

    print("\ninteger square root, and root isolation")
    r = isqrt_ivl(10 ** 20)
    check_true("isqrt_ivl(10^20) encloses 10^10", r.lo <= 10 ** 10 <= r.hi)
    # isolate_root takes integer polynomial coefficients HIGHEST DEGREE FIRST,
    # and an iteration count rather than a tolerance. x^2 - 2 is [1, 0, -2].
    root = isolate_root([1, 0, -2], F(1), F(2), 400)
    lo, hi = root.lo, root.hi
    check_true("isolate_root brackets sqrt(2)",
               lo - F(1, 10 ** 50) <= as_fraction(SQRT2) <= hi + F(1, 10 ** 50),
               f"[{float(lo)}, {float(hi)}]")

    print("\n-- the gate must be able to fail --")
    before = len(FAILURES)
    check("deliberate miss", Ivl(F(1), F(2)), PI)
    if len(FAILURES) == before:
        print("  BROKEN: a value outside its interval was accepted; this suite proves nothing")
        return 1
    FAILURES.pop()
    print("  ok   a value outside its interval is rejected")

    print()
    if FAILURES:
        print(f"FAIL — {len(FAILURES)}: {', '.join(FAILURES)}")
        return 1
    print("PASS — every published value lies inside its computed interval")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
